// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['directives/directives', 'text!templates/link.html'], function(directives, template) {
  'use strict';

  var directive;
  directive = function() {
    return {
      replace: true,
      restrict: 'E',
      scope: {
        url: 'bind'
      },
      template: template,
      transclude: true
    };
  };
  directives.directive('ngLink', [directive]);
  return directive;
});
