// Generated by CoffeeScript 1.3.3
/*global define, describe, beforeEach, module, it, inject, expect
*/

define(['libs/angularMocks', 'filters/twitterfy'], function() {
  'use strict';
  return describe('twitterfy filter', function() {
    beforeEach(module('filters'));
    return it('Twitter username should be prepended with the @ sign', inject([
      'twitterfyFilter', function(twitterfy) {
        var twitterHandle, twitterfied;
        twitterHandle = 'CaryLandholt';
        twitterfied = twitterfy(twitterHandle);
        expect(twitterfied).not.toEqual(twitterHandle);
        return expect(twitterfied).toEqual("@" + twitterHandle);
      }
    ]));
  });
});
