// Generated by CoffeeScript 1.3.1
/*global require, __dirname
*/

(function(express, dir) {
  var app, open;
  app = express.createServer();
  open = function(command) {
    var ostype, spawn, url;
    if (command == null) {
      command = 'open';
    }
    url = "http://localhost:" + (app.address().port);
    ostype = require('os').type();
    if (ostype === 'Windows_NT') {
      command = 'explorer';
    }
    spawn = require('child_process').spawn;
    console.log("launching " + url);
    return spawn(command, [url]);
  };
  return app.configure(function() {
    app.set('view options', {
      layout: false
    });
    app.use(express["static"](dir));
    app.use(app.router);
    app.register('.html', {
      compile: function(str, options) {
        return function(locals) {
          return str;
        };
      }
    });
    app.get('/', function(req, res) {
      return res.render("" + dir + "/index.html");
    });
    return app.listen(3005, function() {
      console.log("Express server listening on port " + (app.address().port) + " in " + app.settings.env + " mode");
      return open();
    });
  });
})(require('express'), __dirname);
