// Generated by CoffeeScript 1.3.3
/*global require, __dirname, process
*/

(function(express, dir, port) {
  var app, isUniqueName, nextId, open, people;
  if (port == null) {
    port = 3005;
  }
  nextId = 0;
  people = [
    {
      "id": "" + (nextId++),
      "name": "Cary",
      "age": "42"
    }, {
      "id": "" + (nextId++),
      "name": "Saasha",
      "age": "5"
    }, {
      "id": "" + (nextId++),
      "name": "Planet",
      "age": "7"
    }
  ];
  isUniqueName = function(name) {
    var person;
    return ((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = people.length; _i < _len; _i++) {
        person = people[_i];
        if (person.name === name) {
          _results.push(name);
        }
      }
      return _results;
    })()).length === 0;
  };
  app = express.createServer();
  open = function(command) {
    var ostype, spawn, url;
    if (command == null) {
      command = 'open';
    }
    url = "http://localhost:" + (app.address().port);
    ostype = require('os').type();
    if (ostype === 'Windows_NT') {
      command = 'explorer';
    }
    spawn = require('child_process').spawn;
    console.log("launching " + url);
    return spawn(command, [url]);
  };
  return app.configure(function() {
    app.set('view options', {
      layout: false
    });
    app.use(express.bodyParser());
    app.use(express["static"](dir));
    app.use(app.router);
    app.register('.html', {
      compile: function(str, options) {
        return function(locals) {
          return str;
        };
      }
    });
    app.get('/', function(req, res) {
      return res.render("" + dir + "/index.html");
    });
    app.get('/people', function(req, res) {
      return res.json(people);
    });
    app.get('/people/details/:id', function(req, res) {
      var current, id, person, _i, _len;
      id = req.params.id;
      for (_i = 0, _len = people.length; _i < _len; _i++) {
        person = people[_i];
        if (parseInt(person.id, 10) === parseInt(id, 10)) {
          current = person;
        }
      }
      return res.json(current);
    });
    app.post('/people', function(req, res) {
      var message, name, person;
      name = req.body.name;
      message = {
        "title": "Duplicate!",
        "message": "" + name + " is a duplicate.  Please enter a new name."
      };
      if (!isUniqueName(name)) {
        return res.send(message, 403);
      }
      person = {
        "id": "" + (nextId++),
        "name": "" + name,
        "age": "0"
      };
      people.push(person);
      return res.json(person);
    });
    return app.listen(port, function() {
      console.log("Express server listening on port " + (app.address().port) + " in " + app.settings.env + " mode");
      return open();
    });
  });
})(require('express'), __dirname, process.argv.splice(2)[0]);
