// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var growl, path, rimraf;
    growl = require('growl');
    path = require('path');
    rimraf = require('rimraf');
    return grunt.registerMultiTask('clean', 'Deletes a directory', function() {
      var exists, message, src, srcFullPath;
      src = this.file.src;
      exists = path.existsSync(src);
      if (!exists) {
        return;
      }
      srcFullPath = path.resolve(src);
      message = "Deleted " + srcFullPath + " directory.";
      rimraf.sync(src);
      grunt.log.writeln(message);
      return growl(message, {
        title: 'Directory Deleted'
      });
    });
  };

}).call(this);
