// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var growl, path, rimraf;
    growl = require('growl');
    path = require('path');
    rimraf = require('rimraf');
    return grunt.registerMultiTask('clean', 'Deletes a directory', function() {
      var dest, destFullPath, exists, message;
      dest = this.file.dest;
      exists = path.existsSync(dest);
      if (!exists) {
        return;
      }
      destFullPath = path.resolve(dest);
      message = "Deleted " + destFullPath + " directory.";
      rimraf.sync(dest);
      grunt.log.writeln(message);
      return growl(message, {
        title: 'Directory Deleted'
      });
    });
  };

}).call(this);
