// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var growl, path, wrench;
    growl = require('growl');
    path = require('path');
    wrench = require('wrench');
    return grunt.registerMultiTask('copy', 'Copies a directory', function() {
      var dest, destFullPath, exists, message, src, srcFullPath;
      src = this.file.src;
      dest = this.file.dest;
      exists = path.existsSync(src);
      if (!exists) {
        return;
      }
      srcFullPath = path.resolve(src);
      destFullPath = path.resolve(dest);
      message = "Copied " + srcFullPath + " to " + destFullPath + ".";
      wrench.copyDirSyncRecursive(src, dest);
      grunt.log.writeln(message);
      return growl(message, {
        title: 'Directory Copied'
      });
    });
  };

}).call(this);
