// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var fs, growl, less, path;
    fs = require('fs');
    growl = require('growl');
    less = require('less');
    path = require('path');
    grunt.registerMultiTask('less', 'Compile LESS to CSS', function() {
      var dest, done, options, src, srcFiles;
      done = this.async();
      src = this.file.src;
      dest = this.file.dest;
      options = this.data.options;
      srcFiles = grunt.file.expandFiles(src);
      return grunt.helper('less', srcFiles, options, function(err, css) {
        if (err) {
          grunt.warn(err);
          done(false);
          return;
        }
        grunt.file.write(dest, css);
        return done();
      });
    });
    return grunt.registerHelper('less', function(srcFiles, options, callback) {
      var compileLessFile;
      compileLessFile = function(src, callback) {
        var parser;
        parser = new less.Parser({
          paths: [path.dirname(src)]
        });
        return fs.readFile(src, 'utf8', function(err, data) {
          if (err) {
            callback(err);
          }
          return parser.parse(data, function(err, tree) {
            var css;
            if (err) {
              callback(err);
            }
            css = null;
            try {
              css = tree.toCSS();
            } catch (e) {
              return callback(e);
            }
            return callback(null, css);
          });
        });
      };
      return grunt.utils.async.map(srcFiles, compileLessFile, function(err, results) {
        if (err) {
          return callback(err);
        }
        return callback(null, results.join(grunt.utils.linefeed));
      });
    });
  };

}).call(this);
