// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var fs, growl, path;
    fs = require('fs');
    growl = require('growl');
    path = require('path');
    return grunt.registerMultiTask('prune', 'Deletes files', function() {
      var files, src;
      src = this.file.src;
      files = grunt.file.expandFiles(src);
      return files.forEach(function(file) {
        return fs.unlinkSync(file);
      });
    });
  };

}).call(this);
