// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var requirejs;
    requirejs = require('requirejs');
    return grunt.registerMultiTask('requirejs', 'Runs the RequireJS Optimizer', function() {
      var config;
      config = this.data;
      return requirejs.optimize(config, function(buildResponse) {
        return grunt.verbose.writeln(buildResponse);
      });
    });
  };

}).call(this);
