// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var growl, path, requirejs;
    growl = require('growl');
    path = require('path');
    requirejs = require('requirejs');
    return grunt.registerMultiTask('requirejs', 'Runs the RequireJS Optimizer', function() {
      var config, dest, destFullPath;
      config = this.data;
      dest = config.out;
      destFullPath = path.resolve(dest);
      return requirejs.optimize(config, function(buildResponse) {
        var message;
        message = "Optimized " + buildResponse;
        return growl(message, {
          title: 'Optimized JavaScript'
        });
      });
    });
  };

}).call(this);
