// Generated by CoffeeScript 1.3.3

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var growl, path, removeNonPrintableCharacters, rimraf;
    growl = require('growl');
    path = require('path');
    rimraf = require('rimraf');
    removeNonPrintableCharacters = function(content) {
      var pattern;
      pattern = /(\t|\r\n|\n|\r)/gm;
      return content.replace(pattern, '');
    };
    return grunt.registerMultiTask('template', 'Compiles a template', function() {
      var compiled, config, content, key, source, src, template, _ref;
      src = this.file.src;
      source = grunt.file.read(src);
      config = this.data;
      _ref = config.includes;
      for (key in _ref) {
        template = _ref[key];
        content = grunt.file.read(template);
        config.includes[key] = removeNonPrintableCharacters(content);
      }
      compiled = grunt.template.process(source, config);
      return grunt.file.write(src, compiled);
      /*
      		environment = config.environment
      
      		obj =
      			scripts: scriptsTemplate
      			styles: stylesTemplate
      			environment: environment
      
      		compiled = grunt.template.process source, obj
      
      		grunt.file.write src, compiled
      */

    });
  };

}).call(this);
