// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';

  var repos, searchHistory, service;
  repos = {};
  searchHistory = [];
  service = function($resource) {
    return {
      repos: repos,
      searchHistory: searchHistory,
      get: function(criteria) {
        searchHistory.push(criteria.user);
        repos = $resource('https://github.com/api/v2/json/repos/show/:user', {
          user: 'CaryLandholt',
          callback: 'JSON_CALLBACK'
        }, {
          query: {
            method: 'JSONP'
          }
        });
        return repos.query(criteria, function(Resource, getResponseHeaders) {
          return console.log('success', Resource, getResponseHeaders());
        }, function(obj) {
          return console.log('error', obj.config, obj.headers(), obj.status);
        });
      }
    };
  };
  services.factory('gitHubService', ['$resource', service]);
  return service;
});
