// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['services/services', 'services/message'], function(services) {
  'use strict';
  return services.factory('gitHub', [
    '$resource', 'message', function($resource, message) {
      var activity, get, repos;
      repos = {
        result: {}
      };
      activity = $resource('https://github.com/api/v2/json/repos/show/:user', {
        callback: 'JSON_CALLBACK'
      }, {
        get: {
          method: 'JSONP'
        }
      });
      get = function(criteria, success, failure) {
        return repos.result = activity.get({
          user: criteria
        }, function() {
          message.publish('search', {
            source: 'GitHub',
            criteria: criteria
          });
          return success.apply(this, arguments);
        }, failure);
      };
      return {
        get: get,
        repos: repos
      };
    }
  ]);
});
