// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';
  return services.factory('messageService', [
    '$rootScope', function($rootScope) {
      return {
        publish: function(name, parameters) {
          return $rootScope.$emit(name, parameters);
        },
        subscribe: function(name, listener) {
          return $rootScope.$on(name, listener);
        }
      };
    }
  ]);
});
