// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';

  var service;
  service = function($resource) {
    return $resource('./scripts/data/people.json', {}, {
      query: {
        method: 'GET',
        isArray: true
      }
    });
  };
  services.factory('myService', ['$resource', service]);
  return service;
});
