// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';
  return services.factory('peopleService', [
    '$resource', function($resource) {
      return $resource('./people', {}, {
        query: {
          method: 'GET',
          isArray: true
        }
      });
    }
  ]);
});
