// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['services/services'], function(services) {
  'use strict';
  return services.factory('people', [
    '$resource', function($resource) {
      var activity, get, people, post;
      people = {
        result: []
      };
      activity = $resource('./people', {
        callback: 'JSON_CALLBACK'
      }, {
        get: {
          method: 'GET',
          isArray: true
        },
        post: {
          method: 'POST'
        }
      });
      get = function(success, failure) {
        return people.result = activity.get(success, failure);
      };
      post = function(name, success, failure) {
        if (name == null) {
          name = "Somebody else";
        }
        return activity.post({
          "name": name
        }, function(person) {
          people.result.push(person);
          if (angular.isFunction(success)) {
            return success.apply(this, arguments);
          }
        }, failure);
      };
      return {
        get: get,
        people: people,
        post: post
      };
    }
  ]);
});
