// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['services/services'], function(services) {
  'use strict';
  return services.factory('people', [
    '$resource', function($resource) {
      var activity, get, people, post;
      people = {
        result: {}
      };
      activity = $resource('./members', {
        callback: 'JSON_CALLBACK'
      }, {
        get: {
          method: 'GET',
          isArray: true
        },
        post: {
          method: 'POST',
          isArray: true
        }
      });
      get = function(success, failure) {
        return people.result = activity.get(success, failure);
      };
      post = function(person, success, failure) {
        if (person == null) {
          person = {
            "name": "Somebody else"
          };
        }
        return people.result = activity.post(person, success, failure);
      };
      return {
        get: get,
        people: people,
        post: post
      };
    }
  ]);
});
