// Generated by CoffeeScript 1.3.2
/*global define
*/

define(['services/services'], function(services) {
  'use strict';

  var people;
  people = {};
  return services.factory('peopleService', [
    '$resource', function($resource) {
      var activity;
      activity = $resource('./members', {
        callback: 'JSON_CALLBACK'
      }, {
        get: {
          method: 'GET',
          isArray: true
        },
        post: {
          method: 'POST',
          isArray: true
        },
        put: {
          method: 'PUT',
          isArray: true
        }
      });
      return {
        people: people,
        get: function() {
          return people = activity.get(function(Resource, getResponseHeaders) {
            return console.log('success', Resource, getResponseHeaders());
          }, function(obj) {
            return console.log('error', obj.config, obj.headers(), obj.status);
          });
        },
        post: function() {
          return people = activity.post({
            "name": "Somebody else"
          }, function(Resource, getResponseHeaders) {
            return console.log('success', Resource, getResponseHeaders());
          }, function(obj) {
            return console.log('error', obj.config, obj.headers(), obj.status, obj.data);
          });
        }
      };
    }
  ]);
});
