// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';

  var searchHistory;
  searchHistory = [];
  return services.factory('searchHistoryService', [
    function() {
      return {
        searchHistory: searchHistory
      };
    }
  ]);
});
