// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['services/services'], function(services) {
  'use strict';

  var searchHistory, service, tweets;
  Array.prototype.clone = function() {
    return Array.apply(null, this);
  };
  Array.prototype.sortIt = Array.prototype.sort;
  Array.prototype.reverseIt = Array.prototype.reverse;
  Array.prototype.sort = function() {
    var tmp;
    tmp = this.clone();
    return tmp.sortIt.apply(tmp, arguments);
  };
  Array.prototype.reverse = function() {
    var tmp;
    tmp = this.clone();
    return tmp.reverseIt.apply(tmp, arguments);
  };
  tweets = {};
  searchHistory = [];
  service = function($resource) {
    return {
      tweets: tweets,
      searchHistory: searchHistory,
      get: function(criteria) {
        searchHistory.push(criteria.q);
        tweets = $resource('http://search.twitter.com/:action', {
          action: 'search.json',
          q: 'twitter',
          callback: 'JSON_CALLBACK'
        }, {
          query: {
            method: 'JSONP'
          }
        });
        return tweets.query(criteria);
      }
    };
  };
  services.factory('twitterService', ['$resource', service]);
  return service;
});
