// Generated by CoffeeScript 1.3.1

(function() {
  'use strict';
  Array.prototype.clone = function() {
    return Array.apply(null, this);
  };
  Array.prototype.sortIt = Array.prototype.sort;
  Array.prototype.reverseIt = Array.prototype.reverse;
  Array.prototype.sort = function() {
    var tmp;
    tmp = this.clone();
    return tmp.sortIt.apply(tmp, arguments);
  };
  return Array.prototype.reverse = function() {
    var tmp;
    tmp = this.clone();
    return tmp.reverseIt.apply(tmp, arguments);
  };
})();
