// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'services/myService'], function(angular, controllers) {
  'use strict';

  var controller;
  controller = function($scope, myService) {
    $scope.name = 'Cary David Landholt';
    return $scope.people = myService.query();
  };
  controllers.controller('firstController', ['$scope', 'myService', controller]);
  return controller;
});
