// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'services/gitHubService'], function(angular, controllers) {
  'use strict';
  return controllers.controller('gitHubController', [
    '$scope', 'gitHubService', function($scope, gitHubService) {
      $scope.searchTerm = '';
      $scope.repos = gitHubService.repos;
      return $scope.search = function(searchTerm) {
        return $scope.repos = gitHubService.get({
          user: searchTerm
        });
      };
    }
  ]);
});
