// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'services/gitHubService'], function(angular, controllers) {
  'use strict';

  var controller;
  controller = function($scope, gitHubService) {
    $scope.searchTerm = '';
    $scope.repos = gitHubService.repos;
    return $scope.search = function(searchTerm) {
      return $scope.repos = gitHubService.get({
        user: searchTerm
      });
    };
  };
  controllers.controller('gitHubController', ['$scope', 'gitHubService', controller]);
  return controller;
});
