// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/gitHub'], function(controllers) {
  'use strict';
  return controllers.controller('gitHub', [
    '$scope', '$rootScope', '$location', 'gitHub', function($scope, $rootScope, $location, service) {
      $scope.searchTerm = '';
      $scope.repos = service.repos;
      $scope.search = function(searchTerm) {
        return $location.path("/github/" + searchTerm);
      };
      return $rootScope.$on('gitHub$afterRouteChange', function(event, currentRoute, priorRoute) {
        $scope.searchTerm = currentRoute.params.searchTerm;
        service.get($scope.searchTerm);
        return $scope.$emit('changeTab#gitHub');
      });
    }
  ]);
});
