// Generated by CoffeeScript 1.3.2
/*global define
*/

define(['angular', 'controllers/controllers', 'services/peopleService'], function(angular, controllers) {
  'use strict';
  return controllers.controller('peopleController', [
    '$scope', '$location', 'peopleService', function($scope, $location, peopleService) {
      $scope.people = peopleService.get();
      return $scope.insertPerson = function() {
        return $scope.people = peopleService.post();
      };
    }
  ]);
});
