// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/people'], function(controllers) {
  'use strict';
  return controllers.controller('personDetails', [
    '$scope', '$rootScope', 'people', function($scope, $rootScope, service) {
      $scope.person = service.person;
      return $rootScope.$on('personDetails$afterRouteChange', function(event, currentRoute, priorRoute) {
        var id;
        id = currentRoute.params.id;
        service.getPerson(id);
        return $scope.$emit('changeTab#people');
      });
    }
  ]);
});
