// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/message'], function(controllers) {
  'use strict';
  return controllers.controller('searchHistory', [
    '$scope', 'message', function($scope, service) {
      $scope.searchHistory = [];
      return service.subscribe('search', function(name, parameters) {
        return $scope.searchHistory.push(parameters);
      });
    }
  ]);
});
