// Generated by CoffeeScript 1.3.2
/*global define
*/

define(['use!angular', 'controllers/controllers', 'services/messageService'], function(angular, controllers) {
  'use strict';

  var searchHistory;
  searchHistory = [];
  return controllers.controller('searchHistoryController', [
    '$scope', 'messageService', function($scope, messageService) {
      $scope.searchHistory = searchHistory;
      return messageService.subscribe('search', function(name, parameters) {
        return $scope.searchHistory.push(parameters);
      });
    }
  ]);
});
