// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers'], function(angular, controllers) {
  'use strict';

  var controller;
  controller = function($scope) {
    return $scope.name = 'Saasha Landholt';
  };
  controllers.controller('secondController', ['$scope', controller]);
  return controller;
});
