// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'text!templates/tweets.html', 'services/twitterService'], function(angular, controllers, template) {
  'use strict';

  var getTemplate;
  getTemplate = function($scope, $compile, template) {
    var element, wrappedTemplate;
    wrappedTemplate = '<div>' + template + '</div>';
    element = angular.element(wrappedTemplate);
    $compile(element)($scope);
    $scope.$eval(element);
    return element;
  };
  return controllers.controller('twitterController', [
    '$scope', '$compile', 'twitterService', function($scope, $compile, twitterService) {
      $scope.searchTerm = '';
      $scope.tweets = twitterService.tweets;
      $scope.template = getTemplate($scope, $compile, template);
      $scope.changeSearchTerm = function(searchTerm) {
        return $scope.searchTerm = searchTerm;
      };
      $scope.search = function(searchTerm) {
        return $scope.tweets = twitterService.get({
          q: searchTerm
        });
      };
      return $scope.changeTemplate = function() {
        return $scope.template = getTemplate($scope, $compile, '<div data-ng-bind="searchTerm"></div>');
      };
    }
  ]);
});
