// Generated by CoffeeScript 1.3.2
/*global define
*/

define(['angular', 'controllers/controllers', 'services/twitterService'], function(angular, controllers) {
  'use strict';
  return controllers.controller('twitterController', [
    '$scope', '$location', 'twitterService', function($scope, $location, twitterService) {
      $scope.searchTerm = '';
      $scope.tweets = {};
      $scope.search = function(searchTerm) {
        return $location.path("/twitter/" + searchTerm);
      };
      return $scope.$on('$afterRouteChange', function(event, currentRoute, priorRoute) {
        var searchTerm;
        if (!currentRoute || !currentRoute.$route || !currentRoute.$route.controller || currentRoute.$route.controller !== 'twitterController') {
          return;
        }
        searchTerm = currentRoute.params.searchTerm;
        if (searchTerm) {
          $scope.searchTerm = searchTerm;
          return $scope.tweets = twitterService.get({
            q: $scope.searchTerm
          });
        }
      });
    }
  ]);
});
