// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['controllers/controllers', 'services/twitter'], function(controllers) {
  'use strict';
  return controllers.controller('twitter', [
    '$scope', '$rootScope', '$location', 'twitter', '$log', function($scope, $rootScope, $location, service, $log) {
      $scope.searchTerm = '';
      $scope.tweets = service.tweets;
      $scope.search = function(searchTerm) {
        return $location.path("/twitter/" + searchTerm);
      };
      return $rootScope.$on('twitter$afterRouteChange', function(event, currentRoute, priorRoute) {
        $scope.searchTerm = currentRoute.params.searchTerm;
        service.get($scope.searchTerm, function(Resource, getResponseHeaders) {}, function(obj) {});
        return $scope.$emit('changeTab#twitter');
      });
    }
  ]);
});
