// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'services/twitterService'], function(angular, controllers) {
  'use strict';

  var controller;
  controller = function($scope, twitterService) {
    return $scope.searchHistory = twitterService.searchHistory;
  };
  controllers.controller('twitterSearchHistoryController', ['$scope', 'twitterService', controller]);
  return controller;
});
