// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['libs/angular', 'controllers/controllers', 'directives/directives', 'filters/filters', 'libs/angular-resource', 'responseInterceptors/responseInterceptors', 'services/services'], function(angular) {
  'use strict';
  return angular.module('app', ['ngResource', 'controllers', 'directives', 'filters', 'responseInterceptors', 'services']);
});
