// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['use!angular', 'controllers/controllers', 'directives/directives', 'filters/filters', 'services/services'], function(angular) {
  'use strict';
  return angular.module('app', ['controllers', 'directives', 'filters', 'services']);
});
