// Generated by CoffeeScript 1.3.3
/*global define
*/

define(['require', 'libs/angular', 'app'], function(require, angular) {
  'use strict';
  return require(['libs/domReady!'], function(document) {
    return angular.bootstrap(document, ['app']);
  });
});
