// Generated by CoffeeScript 1.3.1
/*global require, window
*/

require({
  paths: {
    angular: 'libs/angular',
    angularResource: 'libs/angular-resource',
    text: 'libs/text',
    use: 'libs/use'
  },
  use: {
    angular: {
      attach: 'angular'
    },
    angularResource: {
      deps: ['use!angular']
    }
  }
}, ['use!angular', 'app', 'controllers/gitHubController', 'controllers/searchHistoryController', 'controllers/twitterController', 'directives/link', 'directives/tabs', 'directives/tab', 'filters/twitterfy', 'helpers/array.reverse'], function(angular, app) {
  'use strict';
  return angular.bootstrap(window.document, ['app']);
});
