// Generated by CoffeeScript 1.3.1
/*global define
*/

define(['filters/filters'], function(filters) {
  'use strict';

  var filter;
  filter = function(username) {
    return "@" + username;
  };
  filters.filter('twitterfy', [
    function() {
      return filter;
    }
  ]);
  return filter;
});
